/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChapterIndexRouteImport } from './routes/chapter/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as MailIndexRouteImport } from './routes/mail/index'
import { Route as MailMailingIdRouteImport } from './routes/mail/$mailingId'
import { Route as MailComposeRouteImport } from './routes/mail/compose'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as PartnersOrgIdRouteImport } from './routes/partners/$orgId'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as SchoolsIndexRouteImport } from './routes/schools/index'
import { Route as SchoolsSchoolIdRouteImport } from './routes/schools/$schoolId'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as WebsiteIndexRouteImport } from './routes/website/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdCheckInRouteImport } from './routes/events/$eventId/check-in'
import { Route as EventsEventIdInvitesRouteImport } from './routes/events/$eventId/invites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIndexRoute = ChapterIndexRouteImport.update({
  id: '/chapter/',
  path: '/chapter/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailMailingIdRoute = MailMailingIdRouteImport.update({
  id: '/mail/$mailingId',
  path: '/mail/$mailingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailComposeRoute = MailComposeRouteImport.update({
  id: '/mail/compose',
  path: '/mail/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersOrgIdRoute = PartnersOrgIdRouteImport.update({
  id: '/partners/$orgId',
  path: '/partners/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsIndexRoute = SchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSchoolIdRoute = SchoolsSchoolIdRouteImport.update({
  id: '/schools/$schoolId',
  path: '/schools/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdCheckInRoute = EventsEventIdCheckInRouteImport.update({
  id: '/events/$eventId/check-in',
  path: '/events/$eventId/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdInvitesRoute = EventsEventIdInvitesRouteImport.update({
  id: '/events/$eventId/invites',
  path: '/events/$eventId/invites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/new': typeof EventsNewRoute
  '/mail/$mailingId': typeof MailMailingIdRoute
  '/mail/compose': typeof MailComposeRoute
  '/partners/$orgId': typeof PartnersOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/chapter/': typeof ChapterIndexRoute
  '/events/': typeof EventsIndexRoute
  '/mail/': typeof MailIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/website/': typeof WebsiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/invites': typeof EventsEventIdInvitesRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/new': typeof EventsNewRoute
  '/mail/$mailingId': typeof MailMailingIdRoute
  '/mail/compose': typeof MailComposeRoute
  '/partners/$orgId': typeof PartnersOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/chapter': typeof ChapterIndexRoute
  '/events': typeof EventsIndexRoute
  '/mail': typeof MailIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/people': typeof PeopleIndexRoute
  '/schools': typeof SchoolsIndexRoute
  '/site': typeof SiteIndexRoute
  '/website': typeof WebsiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/invites': typeof EventsEventIdInvitesRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/new': typeof EventsNewRoute
  '/mail/$mailingId': typeof MailMailingIdRoute
  '/mail/compose': typeof MailComposeRoute
  '/partners/$orgId': typeof PartnersOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/chapter/': typeof ChapterIndexRoute
  '/events/': typeof EventsIndexRoute
  '/mail/': typeof MailIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/site/': typeof SiteIndexRoute
  '/website/': typeof WebsiteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/invites': typeof EventsEventIdInvitesRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/events/new'
    | '/mail/$mailingId'
    | '/mail/compose'
    | '/partners/$orgId'
    | '/people/$personId'
    | '/schools/$schoolId'
    | '/chapter/'
    | '/events/'
    | '/mail/'
    | '/partners/'
    | '/people/'
    | '/schools/'
    | '/site/'
    | '/website/'
    | '/api/auth/$'
    | '/events/$eventId/check-in'
    | '/events/$eventId/invites'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/events/new'
    | '/mail/$mailingId'
    | '/mail/compose'
    | '/partners/$orgId'
    | '/people/$personId'
    | '/schools/$schoolId'
    | '/chapter'
    | '/events'
    | '/mail'
    | '/partners'
    | '/people'
    | '/schools'
    | '/site'
    | '/website'
    | '/api/auth/$'
    | '/events/$eventId/check-in'
    | '/events/$eventId/invites'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/events/new'
    | '/mail/$mailingId'
    | '/mail/compose'
    | '/partners/$orgId'
    | '/people/$personId'
    | '/schools/$schoolId'
    | '/chapter/'
    | '/events/'
    | '/mail/'
    | '/partners/'
    | '/people/'
    | '/schools/'
    | '/site/'
    | '/website/'
    | '/api/auth/$'
    | '/events/$eventId/check-in'
    | '/events/$eventId/invites'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  EventsNewRoute: typeof EventsNewRoute
  MailMailingIdRoute: typeof MailMailingIdRoute
  MailComposeRoute: typeof MailComposeRoute
  PartnersOrgIdRoute: typeof PartnersOrgIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  SchoolsSchoolIdRoute: typeof SchoolsSchoolIdRoute
  ChapterIndexRoute: typeof ChapterIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MailIndexRoute: typeof MailIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  SchoolsIndexRoute: typeof SchoolsIndexRoute
  SiteIndexRoute: typeof SiteIndexRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventsEventIdCheckInRoute: typeof EventsEventIdCheckInRoute
  EventsEventIdInvitesRoute: typeof EventsEventIdInvitesRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/': {
      id: '/chapter/'
      path: '/chapter'
      fullPath: '/chapter/'
      preLoaderRoute: typeof ChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/': {
      id: '/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$mailingId': {
      id: '/mail/$mailingId'
      path: '/mail/$mailingId'
      fullPath: '/mail/$mailingId'
      preLoaderRoute: typeof MailMailingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/compose': {
      id: '/mail/compose'
      path: '/mail/compose'
      fullPath: '/mail/compose'
      preLoaderRoute: typeof MailComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$orgId': {
      id: '/partners/$orgId'
      path: '/partners/$orgId'
      fullPath: '/partners/$orgId'
      preLoaderRoute: typeof PartnersOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/': {
      id: '/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof SchoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$schoolId': {
      id: '/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof SchoolsSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/site'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/check-in': {
      id: '/events/$eventId/check-in'
      path: '/events/$eventId/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof EventsEventIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/invites': {
      id: '/events/$eventId/invites'
      path: '/events/$eventId/invites'
      fullPath: '/events/$eventId/invites'
      preLoaderRoute: typeof EventsEventIdInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  EventsNewRoute: EventsNewRoute,
  MailMailingIdRoute: MailMailingIdRoute,
  MailComposeRoute: MailComposeRoute,
  PartnersOrgIdRoute: PartnersOrgIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  SchoolsSchoolIdRoute: SchoolsSchoolIdRoute,
  ChapterIndexRoute: ChapterIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MailIndexRoute: MailIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  SchoolsIndexRoute: SchoolsIndexRoute,
  SiteIndexRoute: SiteIndexRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventsEventIdCheckInRoute: EventsEventIdCheckInRoute,
  EventsEventIdInvitesRoute: EventsEventIdInvitesRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
